name: CLEANER REPORT PIPELINE

on:
  schedule:
    - cron: "20 10 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter ipykernel papermill firebase-admin

      - name: Install Jupyter Kernel
        run: python -m ipykernel install --user --name python3

      - name: Create required folders
        run: |
          mkdir -p data/recommendations
          mkdir -p data/suggestions

      - name: Run 00
        run: |
          papermill "00-outcome_data_cleaner.ipynb" \
            "output/00-outcome_data_cleaner$(date +'%Y%m%d_%H%M').ipynb"

    
      - name: List files in data/recommendations
        run: |
          echo "Listing files in data/recommendations:"
          ls -lah data/recommendations

      # --------------------------------------------------
      # COMMIT OUTPUTS BACK TO GITHUB
      # --------------------------------------------------
      - name: Commit updated output & data folders
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "jamesmedice"
          git config user.email "tiago.sllater@github.com"

          git ls-files -v data/recommendations      
          git rm data/recommendations/trade_suggestions_*.csv
          git commit -m "Daily cleanup of generated trade suggestion files"      

          git status

          git add data/ || true
          git status
          git commit -m "Update pipeline output [skip ci]" || true
          
          git pull --rebase || true
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }} || true