name: KNN REPORT PIPELINE

on:
  schedule:
    - cron: "50 16,19,22 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter ipykernel papermill firebase-admin

      - name: Install Jupyter Kernel
        run: python -m ipykernel install --user --name python3

      # --------------------------------------------------
      # RUN ALL NOTEBOOKS â€” they create CSV/PNG output
      # --------------------------------------------------
      - name: Create required folders
        run: |
          ls -lah
          mkdir -p output
          mkdir -p output/kmeans
          mkdir -p output/random_forest


      - name: Run 016
        run: |
          papermill "016_random_forest.ipynb" \
            "output/016_random_forest$(date +'%Y%m%d_%H%M').ipynb"


      - name: Run 017
        run: |
          papermill "016_random_forest.ipynb" \
            "output/016_random_forest$(date +'%Y%m%d_%H%M').ipynb"


      # --------------------------------------------------
      # Upload to Firebase
      # --------------------------------------------------
      - name: Upload Firebase Data
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python scripts/upload_knn.py

    
      - name: List files in data/kmeans
        run: |
          echo "Listing files in data/kmeans:"
          ls -lah data/kmeans

      # --------------------------------------------------
      # COMMIT OUTPUTS BACK TO GITHUB
      # --------------------------------------------------
      - name: Commit updated output & data folders
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "jamesmedice"
          git config user.email "tiago.sllater@github.com"

          git ls-files -v data/kmeans          
          git rm --cached -f data/kmeans/rank_stocks.csv || true
          git add data/kmeans/rank_stocks.csv
          git rm --cached -f data/kmeans/interesting_stocks.csv || true
          git add data/kmeans/interesting_stocks.csv          

          git status

          git add data/ || true
          git status
          git commit -m "Update pipeline output [skip ci]" || true
          
          git pull --rebase || true
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }} || true